# Generated by Django 3.2.16 on 2022-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleArab', models.CharField(max_length=50)),
                ('titleFrench', models.CharField(max_length=50)),
                ('titleEnglish', models.CharField(max_length=50)),
                ('descriptionArab', models.TextField()),
                ('descriptionFrench', models.TextField()),
                ('descriptionEnglish', models.TextField()),
                ('imageLink', models.ImageField(blank=True, upload_to='Actualities/images/')),
                ('isVideo', models.BooleanField(default=False)),
                ('videoLink', models.FileField(blank=True, upload_to='Actualities/videos')),
                ('Creation_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
