# Generated by Django 3.2.16 on 2022-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('videosLink', models.FileField(upload_to='Videos/')),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
